name: React CI - Build and Test
 
on:
   push:
       branches: [ "main" ]
   pull_request:
       branches: [ "main" ]
 
 
jobs:
   build:
       runs-on: ubuntu-latest
 
       steps: 
       - name: Checkout do Codigo
         uses: actions/checkout@v4
 
       - name: Configurar Node.js
         uses: actions/setup-node@v4
         with:
           node-version: 20
           cache: 'npm'
 
       - name: Instalar dependencias
         run: npm ci
 
       - name: Rodar testes
         run: npm test -- --watchall=false
 
       - name: Rodar build
         run: npm run build
